FROM python:3.12-slim

ENV PATH="/root/.rye/shims:${PATH}"

RUN apt-get update
RUN apt-get install -y git curl
RUN cd /usr/local && sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
RUN git clone https://github.com/taylormonacelli/ringgem /opt/ringgem
RUN task -d /opt/ringgem install-rye-on-linux
RUN mkdir -p /root/my_project
WORKDIR /root/my_project
RUN rye init
RUN rm -rf src
RUN rye pin 3.12
RUN rye add ansible-core
RUN rye add molecule
RUN rye add ansible-navigator
RUN rye sync --quiet

RUN echo cache-buster: $RANDOM
COPY run-expanded /tmp/run-expanded
RUN bash -ex /tmp/run-expanded

COPY entrypoint.sh .
COPY run_test.sh .

ENTRYPOINT ["./entrypoint.sh"]
